[[https://travis-ci.org/pashinin/workgroups2][https://travis-ci.org/pashinin/workgroups2.svg?branch=master]]
[[http://melpa.org/#/workgroups2][file:http://melpa.org/packages/workgroups2-badge.svg]]
[[http://stable.melpa.org/#/workgroups2][file:http://stable.melpa.org/packages/workgroups2-badge.svg]]
* Workgroups for Emacs
Workgroups is a session manager for Emacs.

- It saves all your opened buffers, their location and sizes on disk to restore later
- You can create several workspaces

You can also restore such buffers as: org-agenda, shell, magit-status, help.

Fork it, [[https://github.com/pashinin/workgroups2/wiki/How-to-restore-a-specific-type-of-buffer][add more special buffers support]]. Or even better - fix bugs.

** Install
Just install "workgroups2" from Melpa and activate it with

#+begin_src elisp
(require 'workgroups2)
#+end_src

** Usage
*** Quick Start
Use =M-x wg-create-workgroup= to save current windows layout.

Use =M-x wg-open-workgroup= to open saved windows layout.
*** Enable minor mode =workgroups-mode= (OPTIONAL)
Put below line at the bottom of =.emacs=,
#+begin_src elisp
(workgroups-mode 1)
#+end_src

Most commands are bound to both =<prefix> <key>= and =<prefix> C-<key>=.

By default prefix is: "C-c z" (To change it - see settings below)

#+begin_example
<prefix> <key>
<prefix> c    - create workgroup
<prefix> k    - kill workgroup
<prefix> v    - switch to workgroup
<prefix> C-s  - save session
<prefix> C-f  - load session
#+end_example

If you want to set up this minor mode further:
#+begin_src elisp
(require 'workgroups2)
;; Your settings here

;;(setq wg-session-load-on-start t)    ; default: (not (daemonp))

;; Change prefix key (before activating WG)
(setq wg-prefix-key (kbd "C-c z"))

;; Set your own keyboard shortcuts to reload/save/switch WGs:
;; "s" == "Super" or "Win"-key, "S" == Shift, "C" == Control
(global-set-key (kbd "<pause>")     'wg-reload-session)
(global-set-key (kbd "C-S-<pause>") 'wg-save-session)
(global-set-key (kbd "s-z")         'wg-switch-to-workgroup)
(global-set-key (kbd "s-/")         'wg-switch-to-previous-workgroup)

(workgroups-mode 1)   ; put this one at the bottom of .emacs
#+end_src
** Tips (OPTIONAL)
You can use =M-x customize-group workgroups= to see all variables and
faces to change.

#+begin_src elisp
;; Change workgroups session file
(setq wg-session-file "~/.emacs.d/.emacs_workgroups")

;; What to do on Emacs exit / workgroups-mode exit?
(setq wg-emacs-exit-save-behavior           'save)      ; Options: 'save 'ask nil
(setq wg-workgroups-mode-exit-save-behavior 'save)      ; Options: 'save 'ask nil
#+end_src

Hooks' names can tell when they are executed

#+begin_src elisp
workgroups-mode-hook                    ; when `workgroups-mode' is turned on
workgroups-mode-exit-hook               ; `workgroups-mode' is turned off
wg-after-switch-to-workgroup-hook
#+end_src

## License
workgroups2 is free software: you can redistribute it and/or modify it under the terms of the [[https://raw.githubusercontent.com/redguardtoo/workgroups2/master/LICENSE][GNU General Public License]] as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

workgroups2 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the [[https://raw.githubusercontent.com/redguardtoo/workgroups2/master/LICENSE][GNU General Public License]] for more details.

This extension is based on experimental branch of the [[http://github.com/tlh/workgroups.el][original repo]].
